### ISSUE TITLE
Probleme mit Rosalind Aufgabe 4

### ISSUE THREAD

**Issue by andreaspittroff** [BioInf-Wuerzburg-teaching/linux_and_perl2016#5]
Mein Code an diesem Punkt (sh4id 920f2c3861c40ca8b636f92d3ff0949cdc67dd1f) funktioniert auf allen Testdateien, die ich mir erstelle, nur auf der Rosalind-Datei nicht. Hat noch jemand dieses Problem?

Ich glaube, dass es mit dem Runden des Prozentwertes zusammenhängt, weiß aber nicht wie ich das lösen soll.

**Comment by andreaspittroff** [comment]
Ich habe auch versucht einfach manuell auf 6 Nachkommastellen (wie im Rosalind Beispiel Output) zu runden, aber das hat ebenfalls nicht funktioniert

**Comment by PfaffS** [comment]
Servus Andi, also das problem mit dem Runden hab ich mit dem befehl sprintf() gelöst.

my $rounded = sprintf("%.6f", $largest);

Wenn dass dein problem nicht Löst einfach nochmal melden dann versuch ich mal deinen Code zu verstehen

Gruß Simon

**Comment by andreaspittroff** [comment]
Danke, habs probiert, hat aber leider doch nix geholfen. Hier ist der aktuelle Code drin (shaid 1a3e0aa71f111cca986b4dcbf86eedd3b68eb7bc)  Ich vermute, dass es trotzdem ein output Problem ist. irgendwelche Leerzeichen oder Enterzeichen, die nicht hingehören und deshalb von Rosalind als falsch gewertet werden...

Wie gesagt mein Code rechnet eigentlich bei allen Beispielen, die ich selbst erstelle richtig.

Btw, für die fünfte Aufgabe klappts auch nicht, das liegt aber denke ich daran, dass der Zwischenspeicher nicht groß genug war um alle Zeichen zu kopieren. Da muss ich dann wsl das Ergebnis in ne Datei schreiben lassen und diese hochladen

**Comment by PfaffS** [comment]
Problem#4
Servus, ich hab grad mal schnell drübergeguckt (sry für die verspätung), ich seh grad du testest immer auf der selben Sequenz. Bei Rosalind gibts ja immer tolle beispiele ich würde die nehmen. So testest du immer GC-content auf nur einer Sequenz, im Rosalind werden dir aber 3 gegeben (im Beispiel), es kann also gut sein dass deine Funktion die dir den größten Value ausgibt nicht richtig funktioniert. Dass fällt dir bei einer Sequenz beim Testen dann nicht auf, da es nur diese eine gibt.

Da du meintest dein Kopieren funktioniert evtl nicht richtig, arbeitest du auf Putti (oder Ähnlichem) oder hast du nen Linux installiert egal ob in ner VM (Virtielle Maschine) oder als Hauptbetriebssystem (was der Frank dir raten würde :P ).

Fehler die mir beim schnellen drübergucken aufgefallen sind:

"@Winner[0]=$key;
@Winner[1]=$contents{$key};"
Line 150 - 151
die @ durch $ ersetzen.

---

Bei Problem#5 
Rosalind will im Ergebnis das Stopcodon als naja nichts haben, die Sequenz soll einfach enden, ich weiß nich ob du dein "stop" das du als Stopcodon setzt evtl nicht weg gemacht hast, oder dein 

print "String fehlehrhaft oder zu Ende";

noch drinn war, ich würde übrigens in einer Funktion nichts printen, eine Funktion sollte etwas returnen und nichts printen. 
Bei einem Return würde er auch aus der Funktion rauspringen, was bei einem Fehler z.b. wenn keine DNA / RNA übergeben wurde oder die sequenz nicht genau n*3 lang ist das ganze verkürzen würde bis die Fehlermeldung kommt :)

hier konnte ich jetzt auf die schnelle keine Fehler finden (was nicht heißt dass keiner da sein muss ) 

Gruß Simon

**Comment by andreaspittroff** [comment]
also getestet hab ich auf ner anderen datei mit fünf verschiedenen sequenzen, da funktioniert der so wie er ist. arbeite in ner vm.

den code für aufgabe 5 mussich sowieso nochmal überarbeiten, den wollte ich so eh noch nicht verwenden, aber danke für die anmerkungen ;)

**Comment by andreaspittroff** [comment]
habe aufgabe 4 per Hand überprüft und mein Programm hat richtig gerechnet und ausgespuckt.

es sieht so aus als ob Rosalind die Aufgabe mit falsch gewertet hat, weil ich das ">" vor der SequenzID stehen lassen habe.
Werde mal testen obs daran lag

**Comment by andreaspittroff** [comment]
Problem war tatsächlich das ">" in der Sequenz-ID
