### ISSUE TITLE
Rosalind Aufgabe 5

### ISSUE THREAD

**Issue by andreaspittroff** [BioInf-Wuerzburg-teaching/linux_and_perl2016#7]
Hat jemand die fünfte Aufgabe bereits gelöst?
Mein Code hat so funktioniert wie ich es wollte (von Hand nachgeprüft), allerdings gab mir Rosalind zurück, dass meine Lösung falsch ist.
Zuerst habe ich angenommen, dass man den String einfach ganz normal übersetzen muss (da in der Aufgabe nichts gegenteiliges stand). Das ist allerdings nicht so, da Rosalind einen RNA-Strang gibt, der nicht mit dem Startcodon beginnt und Stopcodons enthält.
Muss man nun erst nach einem Startcodon suchen lassen und dann bis zum Stopcodon translatieren? Was wird erwartet, wenn mehrere Starts und Stops enthalten sind - nur die erste Proteinsequenz?
Der Beispieloutput ist da wenig aufschlussreich und leider gibt es ja keine Möglichkeit einzusehen, welchen Output Rosalind mit dem jeweiligen Datenset erwartet hat...

**Comment by PfaffS** [comment]
Servus Andy, 
Also Rosalind erwartet als Ergebnis die komplette übersetzung und für das Stopcodn NICHTS, meine Sequenz hatte nicht mit einem Startcodon angefangen aber mit einem Stopcodon geendet, ich hab die Sequenz einfach übersetzt und für das Stopcodon nichts gesetzt.

Hoffe das hilft dir weiter,
Gruß Simon

**Comment by andreaspittroff** [comment]
Hmm, ok.
also fürs stopcodon hab ich auch nichts gesetzt,aber lasse meine Sequenz dort auch entsprechend enden.

Meine Sequenz hatte mehrere Start- und Stop-Codons

**Comment by andreaspittroff** [comment]
Hat so funktioniert, auch wenn ich die Aufgabenstellung so mehr als fragwürdig finde...

Das Translatetool von Expasy hat mir 3 Start-Stop-Fenster angezeigt, damit ich Rosalinds Erartungen erfülle, musste mein Programm allerdings alle 3 in eine fortlaufende Proteinsequenz übersetzen. Stop-Codons müssen also einfach übersprungen werden. Nicht wirklich nah am tatsächlichen System.
